### ISSUE TITLE
s3fs acl argument is not supported

### ISSUE THREAD

**Issue by danielgafni** [kedro-org/kedro#1080]
## Description
I have an S3 bucket that requires setting the `acl` to operate.

`s3fs` supports setting the `acl` argument [here](https://fs-s3fs.readthedocs.io/en/latest/#s3fs-constructor)

But when I try to pass it to `client_kwargs` in my `credentials.yml` I get this error:
```
kedro.io.core.DataSetError: Failed while loading data from data set ParquetDataSet(filepath="...", load_args={}, protocol=s3, save_args={}).
_create_client() got an unexpected keyword argument 'acl'
```

## Steps to Reproduce
1. Make an s3 credentials config with acl:

```yml
my_s3:
     client_kwargs:
          aws_access_key_id: ...
          aws_secret_access_key: ...
          acl: 'x-amz-acl: authenticated'  # for example
```

2. Try to use this config to save or load anything

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):  0.17.5
* Python version used (`python -V`): Python 3.8.12
* Operating system and version:

```
NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
```

**Comment by datajoely** [comment]
Can you post your catalog entry?

**Comment by AntonyMilneQB** [comment]
I've just tried this out and can confirm it's a problem. The full traceback is useful here:
```
Traceback (most recent call last):
  File "/Users/antony_milne/kedro_stuff/kedro/kedro/io/core.py", line 182, in load
    return self._load()
  File "/Users/antony_milne/kedro_stuff/kedro/kedro/extras/datasets/pandas/parquet_dataset.py", line 164, in _load
    if self._fs.isdir(load_path):
  File "/Users/antony_milne/miniconda3/envs/spaceflights/lib/python3.8/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/antony_milne/miniconda3/envs/spaceflights/lib/python3.8/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/Users/antony_milne/miniconda3/envs/spaceflights/lib/python3.8/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/Users/antony_milne/miniconda3/envs/spaceflights/lib/python3.8/site-packages/s3fs/core.py", line 1141, in _isdir
    return bool(await self._lsdir(path))
  File "/Users/antony_milne/miniconda3/envs/spaceflights/lib/python3.8/site-packages/s3fs/core.py", line 578, in _lsdir
    await self.set_session()
  File "/Users/antony_milne/miniconda3/envs/spaceflights/lib/python3.8/site-packages/s3fs/core.py", line 417, in set_session
    s3creator = self.session.create_client(
  File "/Users/antony_milne/miniconda3/envs/spaceflights/lib/python3.8/site-packages/aiobotocore/session.py", line 65, in create_client
    return ClientCreatorContext(self._create_client(*args, **kwargs))
TypeError: _create_client() got an unexpected keyword argument 'acl'
```

So basically fsspec calls s3fs, which calls aiobotocore, and that doesn't have the `acl` argument. Here's where `_create_client` is defined: https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/session.py#L67

**Comment by AntonyMilneQB** [comment]
ok, try this out:
```
dataset_name:
  fs_args:
    s3_additional_kwargs:
      ACL: blah
```
or this:
```
dataset_name:
  fs_args:
    acl: blah
```

Note the different case for `acl` vs `ACL`/.

**Comment by MerelTheisenQB** [comment]
Hi @danielgafni do you need more help with this issue or can we close it?

**Comment by danielgafni** [comment]
I'm not using kedro anymore, so I guess you can close the issue...
