### ISSUE TITLE
When telemetry is enabled and internet is down, kedro fails to launch

### ISSUE THREAD

**Issue by pascalwhoop** [kedro-org/kedro#1289]
## Description
When dev'ing offline but with telemetry accepted, kedro won't work
## Context
telemetry shouldn't get in the way of dev productivity. else it will be deleted.

## Steps to Reproduce
`kedro new`
accept telemetry
turn off internet
`kedro catalog list`
-> 
```bash
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pascal_brokmeier/.virtualenvs/conti/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 246, in main
    cli_collection()
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 180, in main
    self._cli_hook_manager.hook.before_command_run(  # pylint: disable=no-member
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/kedro_telemetry/plugin.py", line 80, in before_command_run
    _send_heap_event(
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/kedro_telemetry/plugin.py", line 148, in _send_heap_event
    resp = requests.post(url=HEAP_ENDPOINT, headers=HEAP_HEADERS, data=json.dumps(data))
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/pascal_brokmeier/.virtualenvs/conti/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='heapanalytics.com', port=443): Max retries exceeded with url: /api/track (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10d1d2070>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

## Expected Result
telemetry fails silently 

## Actual Result
crash

## Your Environment
python 3.8, MacOS

**Comment by datajoely** [comment]
Merging with this issue - https://github.com/kedro-org/kedro/issues/1249

**Comment by lorenabalan** [comment]
Closing as resolved in https://github.com/kedro-org/kedro-plugins/pull/6
