### ISSUE TITLE
Error in initializing kedro great

### ISSUE THREAD

**Issue by shreyasanand07** [kedro-org/kedro#1534]
## Description
Error in initializing kedro great

## Context
I am trying to install kedro-great to integrate great expectation with Kedro but the kedro great init command fails giving below error info.

## Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [And so on...]

## Expected Result
Kedro great should be initialized

## Actual Result
Kedro great should be initialized but fails as below

```
-- If you received an error, place it here.
Traceback (most recent call last):
  File "/home/anandshr/miniconda3/envs/daa-eds-jarvis/lib/python3.7/site-packages/kedro/framework/cli/utils.py", line 352, in load_entry_points
    entry_point_commands.append(entry_point.load())
  File "/home/anandshr/miniconda3/envs/daa-eds-jarvis/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/home/anandshr/miniconda3/envs/daa-eds-jarvis/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/anandshr/miniconda3/envs/daa-eds-jarvis/lib/python3.7/site-packages/kedro_great/__init__.py", line 1, in <module>
    from .kedro_great import KedroGreat
  File "/home/anandshr/miniconda3/envs/daa-eds-jarvis/lib/python3.7/site-packages/kedro_great/kedro_great.py", line 10, in <module>
    from great_expectations.datasource.types import BatchMarkers
ImportError: cannot import name 'BatchMarkers' from 'great_expectations.datasource.types' (/home/anandshr/miniconda3/envs/daa-eds-jarvis/lib/python3.7/site-packages/great_expectations/datasource/types/__init__.py)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anandshr/miniconda3/envs/daa-eds-jarvis/bin/kedro", line 10, in <module>
    sys.exit(main())
  File "/home/anandshr/miniconda3/envs/daa-eds-jarvis/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 245, in main
    cli_collection = KedroCLI(project_path=Path.cwd())
  File "/home/anandshr/miniconda3/envs/daa-eds-jarvis/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 160, in __init__
    ("Global commands", self.global_groups),
  File "/home/anandshr/miniconda3/envs/daa-eds-jarvis/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 198, in global_groups
    return [cli, create_cli, *load_entry_points("global")]
  File "/home/anandshr/miniconda3/envs/daa-eds-jarvis/lib/python3.7/site-packages/kedro/framework/cli/utils.py", line 354, in load_entry_points
    raise KedroCliError(f"Loading {name} commands from {entry_point}") from exc
kedro.framework.cli.utils.KedroCliError: Loading global commands from kedro-great = kedro_great:commands

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.7
* Python version used (`python -V`): 3.7.8
* Operating system and version: Window 10

**Comment by yetudada** [comment]
Hi @shreyasanand07! Thanks for raising this issue. I'm unfortunately going to close this issue on the Kedro repository because it should be raised on the `kedro-great` repository instead. The Kedro team only maintains plugins within the [`kedro-org`](https://github.com/kedro-org) and therefore this one is outside of our remit.

**Comment by datajoely** [comment]
I would say check out the pandera library, users are reporting it's much nicer to use than GE
