### ISSUE TITLE
Fix CI issues with Sphinx build

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1783]
### Description
The CI builds are currently failing on the `build_docs` and `docs_linkcheck` builds. They're both failing for the same reason: 

```
Traceback (most recent call last):
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/site-packages/sphinx/application.py", line 346, in build
    self.builder.build_all()
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 259, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/site-packages/sphinx/util/logging.py", line 214, in pending_warnings
    memhandler.flushTo(logger)
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/site-packages/sphinx/util/logging.py", line 179, in flushTo
    logger.handle(record)
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/logging/__init__.py", line 890, in handle
    rv = self.filter(record)
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/logging/__init__.py", line 751, in filter
    result = f.filter(record)
  File "/home/circleci/miniconda/envs/kedro_builder/lib/python3.7/site-packages/sphinx/util/logging.py", line 422, in filter
    raise exc
sphinx.errors.SphinxWarning: /home/circleci/project/docs/build/kedro.rst.rst:24:autosummary: stub file not found 'kedro.kedro.config'. Check your autosummary_generate setting.

Warning, treated as error:
/home/circleci/project/docs/build/kedro.rst.rst:24:autosummary: stub file not found 'kedro.kedro.config'. Check your autosummary_generate setting.
make: *** [Makefile:34: build-docs] Error 2
```

I have managed to reproduce this error in a clean conda environment locally. (It initially passed in an existing env). But haven't been able to pin down what the issue is.

**Comment by AhdraMeraliQB** [comment]
The CI builds are no longer failing. 

![image](https://user-images.githubusercontent.com/90615669/186421284-0f635dae-87ec-4068-bfaa-2ea71323ef85.png)
