### ISSUE TITLE
Fix failing Windows jupyter e2e tests

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#2320]
## Description

Tests are failing on CI with the following output:

```
Scenario: Execute jupyter-notebook target                           # features/jupyter.feature:7
    Given I have prepared a config file                               # features/steps/cli_steps.py:144
    And I have run a non-interactive kedro new with starter "default" # features/steps/cli_steps.py:226
    When I execute the kedro jupyter command "notebook --no-browser"  # features/steps/cli_steps.py:319
    Then jupyter notebook should run on port 8888                     # features/steps/cli_steps.py:545
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000248C3F6A460>, 'Connection to localhost timed out. (connect timeout=1.0)'))
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000248C3FC20D0>, 'Connection to localhost timed out. (connect timeout=1.0)'))
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000248C3FEC460>, 'Connection to localhost timed out. (connect timeout=1.0)'))
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000248C3FC24F0>, 'Connection to localhost timed out. (connect timeout=1.0)'))
HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000248C3FC25E0>, 'Connection to localhost timed out. (connect timeout=1.0)'))
      Traceback (most recent call last):
        File "C:\tools\miniconda3\envs\kedro_builder\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "C:\tools\miniconda3\envs\kedro_builder\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\cli_steps.py", line 556, in check_jupyter_nb_proc_on_port
          util.wait_for(
        File "C:\Users\circleci\project\features\steps\util.py", line 70, in wait_for
          raise WaitForException(
      features.steps.util.WaitForException: func: <function _check_service_up at 0x00000248C1F06F70>, didn't return within specified timeout: 15

```

The same happens for `Scenario: Execute jupyter-lab target`

**Comment by AhdraMeraliQB** [comment]
Closing as resolved by https://github.com/kedro-org/kedro/pull/2331
