### ISSUE TITLE
kedro.io.core.DatasetError: Loading not supported for 'MetricsDataset'

### ISSUE THREAD

**Issue by EloyID** [kedro-org/kedro#3681]
## Description
I cannot load MetricsDataset to my node

## Context
A node that worked before upgrading to the latest kedro version, does not work anymore. I use the metrics as dict variable for some calculations.

## Steps to Reproduce
1. Try to load to a node a `tracking.MetricsDataset`

## Expected Result
Just to load it as a dict

## Actual Result
It fails when loading

```
[03/04/24 17:59:35] INFO     Saving data to                         data_catalog.py:525
                             xgboost_monotonic_price_pca.y_test_pre 
                             dicted (PickleDataset)...
                    INFO     Saving data to                         data_catalog.py:525
                             xgboost_monotonic_price_pca.y_test_inf 
                             erred (PickleDataset)...
                    INFO     Saving data to                         data_catalog.py:525
                             xgboost_monotonic_price_pca.test_metri 
                             cs (MetricsDataset)...
                    INFO     Completed 43 out of 49 tasks       sequential_runner.py:90
                    INFO     Loading data from                      data_catalog.py:483
                             xgboost_unconstrained.train_metrics    
                             (MetricsDataset)...
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\framework\session\session.py", line 392, in run
    run_result = runner.run(
                 ^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\runner.py", line 117, in run
    self._run(pipeline, catalog, hook_or_null_manager, session_id)  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\sequential_runner.py", line 78, in _run
    self._suggest_resume_scenario(pipeline, done_nodes, catalog)
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\runner.py", line 206, in _suggest_resume_scenario
    start_p_persistent_ancestors = _find_persistent_ancestors(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\runner.py", line 249, in _find_persistent_ancestors
    if _has_persistent_inputs(current_node, catalog):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\runner.py", line 290, in _has_persistent_inputs
    if isinstance(catalog._datasets[node_input], MemoryDataset):
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
> c:\pathl\miniconda3\envs\kedro\lib\site-packages\kedro\runner\runner.py(290)_has_persistent_inputs()
-> if isinstance(catalog._datasets[node_input], MemoryDataset):
(Pdb) c
Traceback (most recent call last):
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\sequential_runner.py", line 75, in _run
    run_node(node, catalog, hook_manager, self._is_async, session_id)
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\runner.py", line 331, in run_node
    node = _run_node_sequential(node, catalog, hook_manager, session_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\runner.py", line 412, in _run_node_sequential
    inputs[name] = catalog.load(name)
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\io\data_catalog.py", line 490, in load
    result = dataset.load()
             ^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\io\core.py", line 615, in load
    return super().load()
           ^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\io\core.py", line 193, in load
    return self._load()
           ^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro_datasets\tracking\metrics_dataset.py", line 49, in _load
    raise DatasetError(f"Loading not supported for '{self.__class__.__name__}'")       
kedro.io.core.DatasetError: Loading not supported for 'MetricsDataset'
```

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Pathl\miniconda3\envs\kedro\Scripts\kedro.exe\__main__.py", line 7, in <module>
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\framework\cli\cli.py", line 198, in main
    cli_collection()
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\framework\cli\cli.py", line 127, in main
    super().main(
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\framework\cli\project.py", line 225, in run
    session.run(
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\framework\session\session.py", line 392, in run
    run_result = runner.run(
                 ^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\runner.py", line 117, in run
    self._run(pipeline, catalog, hook_or_null_manager, session_id)  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\sequential_runner.py", line 78, in _run
    self._suggest_resume_scenario(pipeline, done_nodes, catalog)
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\runner.py", line 206, in _suggest_resume_scenario
    start_p_persistent_ancestors = _find_persistent_ancestors(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\runner.py", line 249, in _find_persistent_ancestors
    if _has_persistent_inputs(current_node, catalog):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pathl\miniconda3\envs\kedro\Lib\site-packages\kedro\runner\runner.py", line 290, in _has_persistent_inputs
    if isinstance(catalog._datasets[node_input], MemoryDataset):
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'xgboost_monotonic_price_pca.y_test_inferred#model_output@pickle'
```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.19.3
* Python version used (`python -V`): Python 3.11.8
* Operating system and version: Microsoft Windows [Version 10.0.22621.1928]

**Comment by EloyID** [comment]
Well I just saw in the documentation that now is write-only but it's a pity, we don't lose anything to make it loadable :)

**Comment by merelcht** [comment]
Hi @EloyID, thanks for opening this issue. This is indeed a feature of `MetricDataset` and not a bug. This particular dataset was introduced to facilitate experiment tracking in Kedro Viz and is not meant to be loaded directly in nodes. The dataset is based on `json_dataset.JSONDataset` so I'd suggest just using that for loading.
