### ISSUE TITLE
UnboundLocalError: cannot access local variable 'pipelines_package' where it is not associated with a value

### ISSUE THREAD

**Issue by JenspederM** [kedro-org/kedro#3847]
## Description
Error is throw when trying to print `find_pipelines` from the `kedro.framework.project` module.

## Context
Unable to use find_pipelines

## Steps to Reproduce
1. Add `print(find_pipelines())` to the bottom of the `pipeline_regitry.py` file
2. Run the file `python ./src/<project>/pipeline_regitry.py`

## Expected Result
A dict of pipelines.

## Actual Result
I get the following error:
```
[05/02/24 18:05:49] WARNING  /Users/.../.venv/lib/python3.12/site-pac warnings.py:110
                             kages/kedro/framework/project/__init__.py:350: UserWarning: An error                      
                             occurred while importing the 'None.pipeline' module. Nothing defined                      
                             therein will be returned by 'find_pipelines'.                                             
                                                                                                                       
                             Traceback (most recent call last):                                                        
                               File                                                                                    
                             "/Users/.../.venv/lib/python3.12/site-pa                
                             ckages/kedro/framework/project/__init__.py", line 347, in find_pipelines                  
                                 pipeline_module = importlib.import_module(pipeline_module_name)                       
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                       
                               File                                                                                    
                             "/Users/.../.rye/py/cpython@3.12.2/install/lib/python3.12/i                
                             mportlib/__init__.py", line 90, in import_module                                          
                                 return _bootstrap._gcd_import(name[level:], package, level)                           
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                           
                               File "<frozen importlib._bootstrap>", line 1387, in _gcd_import                         
                               File "<frozen importlib._bootstrap>", line 1360, in _find_and_load                      
                               File "<frozen importlib._bootstrap>", line 1310, in                                     
                             _find_and_load_unlocked                                                                   
                               File "<frozen importlib._bootstrap>", line 488, in                                      
                             _call_with_frames_removed                                                                 
                               File "<frozen importlib._bootstrap>", line 1387, in _gcd_import                         
                               File "<frozen importlib._bootstrap>", line 1360, in _find_and_load                      
                               File "<frozen importlib._bootstrap>", line 1324, in                                     
                             _find_and_load_unlocked                                                                   
                             ModuleNotFoundError: No module named 'None'                                               
                                                                                                                       
                               warnings.warn(                                                                          
                                                                                                                       
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/.../project/src/project/pipeline_registy.py:21 in <module>                                                                             │
│                                                                                                  │
│   18                                                                                             │
│   19                                                                                             │
│   20 if __name__ == "__main__":                                                                  │
│ ❱ 21 │   print(register_pipelines())                                                             │
│   22                                                                                             │
│                                                                                                  │
│ /Users/.../project/src/project/pipeline_registry.py:15 in register_pipelines                                                                   │
│                                                                                                  │
│   12 │   Returns:                                                                                │
│   13 │   │   A mapping from pipeline names to ``Pipeline`` objects.                              │
│   14 │   """                                                                                     │
│ ❱ 15 │   pipelines = find_pipelines()                                                            │
│   16 │   pipelines["__default__"] = sum(pipelines.values())                                      │
│   17 │   return pipelines                                                                        │
│   18                                                                                             │
│                                                                                                  │
│ /Users/.../.venv/lib/python3.12/site-packages/kedro/framework/project/__init__.py:367 in find_pipelines                                                        │
│                                                                                                  │
│   364 │   │   if str(exc) == f"No module named '{PACKAGE_NAME}.pipelines'":                      │
│   365 │   │   │   return pipelines_dict                                                          │
│   366 │                                                                                          │
│ ❱ 367 │   for pipeline_dir in pipelines_package.iterdir():                                       │
│   368 │   │   if not pipeline_dir.is_dir():                                                      │
│   369 │   │   │   continue                                                                       │
│   370                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnboundLocalError: cannot access local variable 'pipelines_package' where it is not associated with a value
```

## Your Environment
* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.19.5
* Python version used (`python -V`): Python 3.12.2 using rye as package manager
* Operating system and version: M1 Mac with macOS Sonoma Version 14.4.1

**Comment by merelcht** [comment]
Hi @JenspederM, thanks for flagging this issue. Can I ask what your use case is for printing the result of `find_pipelines()`? 

This method has been added to enable auto discovery of pipelines and does some stuff in the back to make sure your project and its modules are discoverable (https://docs.kedro.org/en/stable/nodes_and_pipelines/pipeline_registry.html). It's meant to run as part of a "regular" Kedro flow where it's preceded by certain project setup methods. You can fix your script by calling `bootstrap_project()` before `find_pipelines()` (https://docs.kedro.org/en/stable/kedro_project_setup/session.html#bootstrap-project-and-configure-project). However, I would only recommend doing that for exploration and not if you're planning to run that code in production. 

Let me know if this makes sense!

**Comment by JenspederM** [comment]
Hi @merelcht, 

I am using `find_pipelines()` to generate databricks assets bundle resources. I am working on a template for asset bundles that uses Kedro for defining pipelines and dependencies and databricks workflows for scheduling. You can find the project [here](https://github.com/JenspederM/databricks-kedro-bundle)

Thanks for the suggesting `bootstrap_project()`. For now, I have been using `configure_project(<package-name>)` as used in `databricks_run.py` in the `databricks-iris` starter.

**Comment by astrojuanlu** [comment]
I'd say, regardless of use case, raising an `UnboundLocalError` from internal code should not happen, but a more informative error instead.

> I have been thinking of making a cookiecutter for Kedro as well. Do you think there would be any interest in this?

Of course! When you get to do it, we can promote it on https://github.com/kedro-org/awesome-kedro

Also consider exploring https://github.com/copier-org/copier/, a modern alternative to cookiecutter

**Comment by JenspederM** [comment]
The only problem that I haven't really found a solution for is how I would get the workspace host from the users' Databricks config without using the Databricks CLI.

**Comment by astrojuanlu** [comment]
Moving this to our Inbox so that we can look at it and it doesn't get lost.

**Comment by astrojuanlu** [comment]
> IMO global variables can be quite dangerous when used like this, so I would probably advice for redesigning this logic to remove the use of globals.

For the record, I agree

**Comment by jbbqqf** [comment]
Hi! Triaging older issues this week — I think this one has shipped and can be closed.

The `UnboundLocalError` reported here no longer occurs on `main`:

- `find_pipelines()` now guards on `PACKAGE_NAME is None` upfront and raises a descriptive `RuntimeError("'find_pipelines' cannot be called before the project is configured. Call 'configure_project' first.")` — see [`kedro/framework/project/__init__.py:496-500`](https://github.com/kedro-org/kedro/blob/main/kedro/framework/project/__init__.py#L496-L500). Running `python src/<project>/pipeline_registry.py` directly (the original repro) now hits this clear error instead of a traceback through `pipelines_package`.
- `pipeline_obj` is explicitly initialised to `None` before any conditional assignment, so the `UnboundLocalError` path the original traceback walked through is gone — see [`kedro/framework/project/__init__.py:510`](https://github.com/kedro-org/kedro/blob/main/kedro/framework/project/__init__.py#L510).

Would you mind closing this out? If you still hit an `UnboundLocalError` (rather than the new `RuntimeError`) on a recent Kedro release, point me at the repro and I'll dig further.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against the current `main` branch.)

**Comment by merelcht** [comment]
Thanks @jbbqqf from quickly checking your links it does look like we fixed this issue while solving something else 🙂 I'll let the Kedro Wizard check this properly to see if it can be closed.

**Comment by JenspederM** [comment]
Can confirm that this now surfaces a much more relevant error :) Thank you for the amazing work!

```
[05/22/26 10:37:47] INFO     Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.                               __init__.py:275
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/jens.p.meldgaard/dev/hs-kedro-demo/src/hs_kedro_demo/pipeline_registry.py:19 in <module>  │
│                                                                                                  │
│   16 │   return pipelines                                                                        │
│   17                                                                                             │
│   18 if __name__ == "__main__":                                                                  │
│ ❱ 19 │   print(find_pipelines())                                                                 │
│   20                                                                                             │
│                                                                                                  │
│ /Users/jens.p.meldgaard/dev/hs-kedro-demo/.venv/lib/python3.13/site-packages/kedro/framework/pro │
│ ject/__init__.py:449 in find_pipelines                                                           │
│                                                                                                  │
│   446 │   │   │   If ``raise_errors`` is ``True``, see Raises section instead.                   │
│   447 │   """                                                                                    │
│   448 │   if PACKAGE_NAME is None:                                                               │
│ ❱ 449 │   │   raise RuntimeError(                                                                │
│   450 │   │   │   "'find_pipelines' cannot be called before the project is configured. "         │
│   451 │   │   │   "Call 'configure_project' first."                                              │
│   452 │   │   )                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: 'find_pipelines' cannot be called before the project is configured. Call 'configure_project' first.
```

**Comment by JenspederM** [comment]
Can also confirm that it works if you bootstrap the project beforehand:

```py
"""Project pipelines."""

from __future__ import annotations

from pathlib import Path

from kedro.framework.project import find_pipelines
from kedro.framework.session import KedroSession
from kedro.framework.startup import bootstrap_project
from kedro.pipeline import Pipeline


def register_pipelines() -> dict[str, Pipeline]:
    """Register the project's pipelines.

    Returns:
        A mapping from pipeline names to ``Pipeline`` objects.
    """
    pipelines = find_pipelines(raise_errors=True)
    pipelines["__default__"] = sum(pipelines.values())
    return pipelines


if __name__ == "__main__":
    p = Path(__file__).parent.parent.parent
    bootstrap_project(p)
    with KedroSession.create(project_path=p) as session:
        print(find_pipelines())
```

**Comment by merelcht** [comment]
Thanks for verifying @JenspederM! I'll close this issue 🙂
