### ISSUE TITLE
Clearer underlying dataset issues

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro#3971]
## Description

A user reported that Kedro was unable to read the CSV, they get the following logs in AWS:
![image](https://github.com/kedro-org/kedro/assets/35801847/03d57ae6-c8ae-4d82-919e-a65cdf3b43ee)

The "No columns to parse from file" is being thrown by the underlying pandas implementation in [this file](https://github.com/pandas-dev/pandas/blob/a89f20853591516b4ba45a1fbadbf645247d133e/pandas/io/parsers/python_parser.py#L226)

It would be helpful if Kedro could bubble up that the error is thrown in `pandas.io.parsers.python_parser` so that it is clear where the issue lies. The error above, mentions `kedro.io.core.DatasetError` is it not possible to do the same?

**Comment by astrojuanlu** [comment]
It is unclear why those logs don't show tracebacks.

Anyway, the current implementation of `AbstractDataset` is responsible for that `DatasetError`:

https://github.com/kedro-org/kedro/blob/adfc593bcd2f1b74676e7ab7c1a3b9c168b7257f/kedro/io/core.py#L192-L202

**Comment by datajoely** [comment]
They must be in the `exc` object somewhere, I refuse to believe otherwise

**Comment by ElenaKhaustova** [comment]
Thank you @datajoely! Could you please provide some more context on what AWS service was used to run kedro pipeline? We would like to check if the service is filtering the error messages as it seems like we always showcase the entire error log.

**Comment by datajoely** [comment]
I've asked the user to comment here to double check, but I think it was:

> Docker image running on AWS ECS

**Comment by astrojuanlu** [comment]
First, I amend [my comment above](https://github.com/kedro-org/kedro/issues/3971#issuecomment-2198765655): the traceback is there (`File /usr/local/...`).

The problem of `AbstractDataset` hiding the real error has been mentioned in other places (https://github.com/kedro-org/kedro/issues/1936#issuecomment-1727172650, https://github.com/kedro-org/kedro/issues/2199#issuecomment-2101008300) although I don't think we have an issue for it (@ElenaKhaustova?). If that's the case, maybe we can keep this issue open?

**Comment by astrojuanlu** [comment]
In #2943 we partly addressed the issue of unclear errors with datasets. Yet we have a bit more evidence about this still being a problem.

For example: https://kedro.hall.community/running-kedroviz-on-docker-without-installing-the-library-H0d61LTldx29#bae33c48-aa82-447b-82e7-80486a95ecef

The user was getting

```
Class 'projx.models.audio.io.LargeModel' not found, is this a typo?
```

but the actual underlying error was:

```
>>> from projx.models.audio.io import LargeModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/src/projx/models/audio/__init__.py", line 1, in <module>
    from .base import LAM
  File "/app/src/projx/models/audio/base.py", line 1, in <module>
    from elevenlabs.client import ElevenLabs
ModuleNotFoundError: No module named 'elevenlabs'
```

Another internal user reported this today.

**Comment by astrojuanlu** [comment]
Should we close this as duplicate of https://github.com/kedro-org/kedro/issues/4577 then?

**Comment by merelcht** [comment]
I think this will be solved by #4580 and #4630
