### ISSUE TITLE
[KED-3075] Using CachedDataSet and ParallelRunner together fails

### ISSUE THREAD

**Issue by Minyus** [kedro-org/kedro#673]
## Description
Using CachedDataSet and ParallelRunner together fails.

## Context
CachedDataSet and ParallelRunner are often used to make the pipeline run faster, but using both with Kedro 0.17.0 fails.

## Steps to Reproduce
1.  Run `kedro new --starter=pandas-iris` and generate the Kedro project.
2.  Add the following to `conf/base/catalog.yml`.

```yaml
example_model:
  type: CachedDataSet
  dataset: 
    type: pickle.PickleDataSet
    filepath: /tmp/model.pkl
```
3. Run `kedro run -p`

## Expected Result
Complete without error.

## Actual Result
Tell us what happens instead.

```
2021-01-18 05:33:15,557 - kedro.pipeline.node - ERROR - Node `predict: predict([example_model,example_test_x]) -> [example_predictions]` failed with error: 
unsupported operand type(s) for *: 'float' and 'object'
2021-01-18 05:33:15,566 - kedro.runner.parallel_runner - WARNING - There are 2 nodes that have not run.
You can resume the pipeline run by adding the following argument to your previous command:
  --from-nodes "predict,report"
2021-01-18 05:33:15,587 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kedro/runner/parallel_runner.py", line 145, in _run_node_synchronization
    return run_node(node, catalog, is_async, run_id)
  File "/opt/conda/lib/python3.7/site-packages/kedro/runner/runner.py", line 212, in run_node
    node = _run_node_sequential(node, catalog, run_id)
  File "/opt/conda/lib/python3.7/site-packages/kedro/runner/runner.py", line 297, in _run_node_sequential
    outputs = _call_node_run(node, catalog, inputs, is_async, run_id=run_id)
  File "/opt/conda/lib/python3.7/site-packages/kedro/runner/runner.py", line 265, in _call_node_run
    raise exc
  File "/opt/conda/lib/python3.7/site-packages/kedro/runner/runner.py", line 255, in _call_node_run
    outputs = node.run(inputs)
  File "/opt/conda/lib/python3.7/site-packages/kedro/pipeline/node.py", line 466, in run
    raise exc
  File "/opt/conda/lib/python3.7/site-packages/kedro/pipeline/node.py", line 459, in run
    outputs = self._run_with_dict(inputs, self._inputs)
  File "/opt/conda/lib/python3.7/site-packages/kedro/pipeline/node.py", line 520, in _run_with_dict
    return self._decorated_func(**kwargs)
  File "/data/kedro_proj/pi/src/pi/pipelines/data_science/nodes.py", line 88, in predict
    result = _sigmoid(np.dot(X, model))
  File "<__array_function__ internals>", line 6, in dot
TypeError: unsupported operand type(s) for *: 'float' and 'object'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 696, in main
    cli_collection(**cli_context)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/kedro_proj/pi/src/pi/cli.py", line 236, in run
    pipeline_name=pipeline,
  File "/opt/conda/lib/python3.7/site-packages/kedro/framework/session/session.py", line 414, in run
    run_result = runner.run(filtered_pipeline, catalog, run_id)
  File "/opt/conda/lib/python3.7/site-packages/kedro/runner/runner.py", line 100, in run
    self._run(pipeline, catalog, run_id)
  File "/opt/conda/lib/python3.7/site-packages/kedro/runner/parallel_runner.py", line 350, in _run
    node = future.result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: unsupported operand type(s) for *: 'float' and 'object'

```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.0
* Python version used (`python -V`): 3.7.7
* Operating system and version: Ubuntu 18.04.5 LTS

**Comment by Minyus** [comment]
Related to https://github.com/quantumblacklabs/kedro/issues/420 @deepyaman

**Comment by Minyus** [comment]
Can anyone help on this issue?

**Comment by Minyus** [comment]
Hi @deepyaman  @yetudada , could you please help on this issue?

**Comment by lorenabalan** [comment]
@Minyus is this still an issue with latest Kedro version?

**Comment by SwePalm** [comment]
@lorenabalan  i was able to reproduce this issue with Kedro version 0.17.4, python 3.8.10, Ubuntu 20.04 LTS

**Comment by idanov** [comment]
Hi @Minyus , thank you for reporting the issue! Unfortunately I don't think we'll add support for using `CachedDataSet` with the `ParallelRunner`. Making `MemoryDataSet` and `CachedDataSet` to work with multiprocessing will make those datasets overly complicated and we do not plan to do so in the near future. However if you fancy giving it a try, you can create a custom `CachedDataSet` leveraging the newly introduced in Python 3.8 [SharedMemory](https://docs.python.org/3.8/library/multiprocessing.shared_memory.html). Kedro still supports versions prior to 3.8 and we cannot this class unfortunately, which would make the implementation of a multiprocessing-friendly `CachedDataSet` and `MemoryDataSet` classes much less complicated.

In the meanwhile, we should mark this dataset as non-usable by the `ParallelRunner` the same way we do for `MemoryDataSet` here: https://github.com/kedro-org/kedro/blob/main/kedro/runner/parallel_runner.py#L195-L238

**Comment by MerelTheisenQB** [comment]
Closing this issue. We'll make it clear that `CachedDataSet` cannot be used with the `ParallelRunner`
