### ISSUE TITLE
Update Data validation tutorial with Great Expectations

### ISSUE THREAD

**Issue by IonutBarbuMcK** [kedro-org/kedro#978]
## Description
The tutorial for building a Great Expectations Kedro hook https://kedro.readthedocs.io/en/latest/07_extend_kedro/02_hooks.html#add-data-validation is incomplete/outdated and leads to failed pipeline run

Could it be that following steps are missing from this tutorial?
* setting up the GE directory
* how to define the expectations suite `json`  files for the two datasets

## Context
I was trying to build a data validation hook  for our project using GE following the tutorial

## Steps to Reproduce
1. navigate to https://kedro.readthedocs.io/en/latest/07_extend_kedro/02_hooks.html#add-data-validation
2. follow the steps in the tutorial: install GE, implement the hooks, register the hooks implementation
3. execute `kedro run` 

## Expected Result
successful `kedro run` 

## Actual Result
Tell us what happens instead.

```
2021-10-21 16:25:01,586 - kedro.io.data_catalog - INFO - Saving data to `preprocessed_shuttles` (CSVDataSet)...
2021-10-21 16:25:02,146 - kedro.runner.sequential_runner - INFO - Completed 1 out of 6 tasks
2021-10-21 16:25:02,146 - kedro.io.data_catalog - INFO - Loading data from `companies` (CSVDataSet)...
2021-10-21 16:25:02,205 - kedro.runner.sequential_runner - WARNING - There are 5 nodes that have not run.
You can resume the pipeline run by adding the following argument to your previous command:
  --from-nodes "preprocess_companies_node,create_model_input_table_node,split_data_node"
2021-10-21 16:25:02,236 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
Traceback (most recent call last):
  File "c:\miniconda3\envs\opm_pred\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\miniconda3\envs\opm_pred\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3\envs\opm_pred\Scripts\kedro.exe\__main__.py", line 7, in <module>
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\kedro\framework\cli\cli.py", line 265, in main
    cli_collection()
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\kedro\framework\cli\cli.py", line 210, in main
    super().main(
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Ionut Barbu\Box Sync\Git\Kedro\kedro-tutorial\src\kedro_tutorial\cli.py", line 160, in run
    session.run(
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\kedro\framework\session\session.py", line 408, in run
    run_result = runner.run(filtered_pipeline, catalog, run_id)
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\kedro\runner\runner.py", line 106, in run
    self._run(pipeline, catalog, run_id)
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\kedro\runner\sequential_runner.py", line 90, in _run
    run_node(node, catalog, self._is_async, run_id)
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\kedro\runner\runner.py", line 218, in run_node
    node = _run_node_sequential(node, catalog, run_id)
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\kedro\runner\runner.py", line 302, in _run_node_sequential
    additional_inputs = _collect_inputs_from_hook(
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\kedro\runner\runner.py", line 234, in _collect_inputs_from_hook
    hook_response = hook_manager.hook.before_node_run(  # pylint: disable=no-member
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\Ionut Barbu\Box Sync\Git\Kedro\kedro-tutorial\src\kedro_tutorial\hooks.py", line 83, in before_node_run
    self._run_validation(catalog, inputs, run_id)
  File "C:\Users\Ionut Barbu\Box Sync\Git\Kedro\kedro-tutorial\src\kedro_tutorial\hooks.py", line 103, in _run_validation
    expectation_context = ge.data_context.DataContext()
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\great_expectations\data_context\data_context.py", line 2300, in __init__
    context_root_dir = self.find_context_root_dir()
  File "c:\miniconda3\envs\opm_pred\lib\site-packages\great_expectations\data_context\data_context.py", line 2427, in find_context_root_dir
    raise ge_exceptions.ConfigNotFoundError()
great_expectations.exceptions.ConfigNotFoundError: Error: No great_expectations directory was found here!
    - Please check that you are in the correct directory or have specified the correct directory.
    - If you have never run Great Expectations in this project, please run `great_expectations init` to get started.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used: 0.17.4
* Python version used : 3.8.11
* Operating system and version: Windows 10
* great expectations:  0.13.38

**Comment by ejohnson-amerilife** [comment]
@limdauto, i copied your hooks.py from that repo you linked (https://github.com/limdauto/europython-2021-demo), however when i switched out `before_dataset_saved` with `before_node_run`, the pipeline errors out with: 
> hookimpl definition: before_node_run(dataset_name: str, data: Any)
Argument(s) {'data', 'dataset_name'} are declared in the hookimpl but can not be found in the hookspec

Do you know how to make your hook compatible with `before_node_run`?
Thanks for your help!

**Comment by ejohnson-amerilife** [comment]
Thank you @limdauto! Your example repo allowed me to get Great Expectations v3 API integrated into my kedro pipeline.
Looking forward to your update in the kedro docs.

**Comment by MerelTheisenQB** [comment]
For people coming here through **Hacktoberfest**: The docs on integrating Great expectations with Kedro via hooks need to be updated to work with the latest versions of both tools: https://kedro.readthedocs.io/en/stable/hooks/examples.html#add-data-validation

**Comment by jstammers** [comment]
Hi, I'm not sure if my issue is related, but I've followed the documentation to add some data validation of some `SparkDatasets` that get created during some of my pipelines (with some slight modification to use a batch of data that exists at run-time).
I've noticed some fairly significant performance issues with this, which I think is due to the fact that these validations are being run before the datasets are saved (and are persisted to disk). 
Do you have any recommendations for a better approach when using spark? My first thought was to hook into the `after_dataset_saved` method. Would this still work for  `MemoryDataSet` objects that are not inputs to another node?

**Comment by merelcht** [comment]
This was completed in https://github.com/kedro-org/kedro/pull/2172
